plugins:
  - uses:
    - plugin: http://localhost:4004
      with:
        matchThreshold: 0.95
        warningThreshold: 0.75
        jobMatchingThreshold: 0.75
  - uses:
      - plugin: https://ubiquity-os-command-wallet-main.ubiquity.workers.dev
  
