plugins:
  - uses:
    - plugin: http://localhost:4004
      with:
        matchThreshold: 0.95
        warningThreshold: 0.75
        jobMatchingThreshold: 0.75
  - uses:
      - plugin: http://localhost:4002
  - uses:
      - plugin: http://localhost:4000
  
